language: node_js
node_js:
  - "6"
email:
  on_failure: change
  on_success: never
services:
  - xvfb
before_install:
  - npm config set registry https://:2017-06-03T19%3A29%3A23.765Z@time-machines-npm.sealsecurity.io/
before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
